name: Build and Deploy FrontendApp to ECS

on:
  push:
    branches:
      - main 

env:

  ECR_FRONTEND_IMAGE: "scaninfoga-web"
  AWS_DEFAULT_REGION: "ap-south-1"
  ECS_CLUSTER: "scaninfoga-web-cluster"
  ECS_FRONTEND_SERVICE: "scaninfoga-web-app-service"
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU for amd64
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        if: runner.os == 'Linux'

      - name: Set up Docker for amd64
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 123938353815.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/amd64 -t scaninfoga-web .
          docker tag scaninfoga-web 123938353815.dkr.ecr.ap-south-1.amazonaws.com/scaninfoga-web:latest
          docker push 123938353815.dkr.ecr.ap-south-1.amazonaws.com/scaninfoga-web:latest

      - name: Deploy to ECS
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: ecs update-service --cluster scaninfoga-web-cluster --service scaninfoga-web-app-service --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-south-1"
